### ISSUE TITLE
Amount of words is hardcoded in MainBot.py

### ISSUE THREAD

**Issue by OliverCordingl1** [ThisIsNoahEvans/Dictionary-Bot#2]
The amount of words in the words.txt is hardcoded inside the FOR loop inside MainBot.py. This is bad practice as if the amount of words changes for whatever reason, errors could be caused.

**Comment by ThisIsNoahEvans** [comment]
Thanks for this. I'm not planning to change the words.txt file or its contents but if I do, I will edit the loop.
